### ISSUE TITLE
Adapt facicon for system dark mode

### ISSUE THREAD

**Issue by glebfox** [Haulmont/jmix-sampler#22]
### Solution

**Chome**

<img width="92" alt="Screenshot 2021-06-14 at 17 05 43" src="https://user-images.githubusercontent.com/6077149/121897274-3fa90600-cd33-11eb-82a8-b12ac650d0ce.png">
<img width="88" alt="Screenshot 2021-06-14 at 17 05 52" src="https://user-images.githubusercontent.com/6077149/121897280-40da3300-cd33-11eb-9791-7bac3b2c2bc7.png">

**Safari**

<img width="96" alt="Screenshot 2021-06-14 at 17 06 53" src="https://user-images.githubusercontent.com/6077149/121897298-46d01400-cd33-11eb-918a-43c1ca1a568e.png">
<img width="90" alt="Screenshot 2021-06-14 at 17 06 33" src="https://user-images.githubusercontent.com/6077149/121897293-446dba00-cd33-11eb-8dd8-9d1cfad59671.png">

For QA:

**Note:** Page refresh is required to update favicon

Test on sampler dev environment

**Comment by konyashkina** [comment]
Tested on sampler dev environment. Passed.
