### ISSUE TITLE
A sample of PropertyFilter and other filter components

### ISSUE THREAD

**Issue by glaschenko** [Haulmont/jmix-sampler#52]
It is important to demonstrate the new easy way to create custom filters

**Comment by GlebDurygin** [comment]
@glaschenko 
The current version of the project already has several samples for the `PropertyFilter`, `JpqlFilter`, `GroupFilter` and `Filter` components:
* Filter with filter components:
1) https://demo.jmix.io/sampler/#main/0/sample?id=filter-multiple-conditions
2) https://demo.jmix.io/sampler/#main/1/sample?id=filter-group-condition
3) https://demo.jmix.io/sampler/#main/2/sample?id=filter-property-condition
4) https://demo.jmix.io/sampler/#main/3/sample?id=filter-jpql-condition
5) https://demo.jmix.io/sampler/#main/4/sample?id=filter-add-condition
6) https://demo.jmix.io/sampler/#main/5/sample?id=filter-programmatically-defined
* PropertyFilter
1) https://demo.jmix.io/sampler/#main/6/sample?id=propertyfilter-simple
2) https://demo.jmix.io/sampler/#main/7/sample?id=propertyfilter-operationeditable
3) https://demo.jmix.io/sampler/#main/8/sample?id=propertyfilter-keyvalue
4) https://demo.jmix.io/sampler/#main/9/sample?id=propertyfilter-customfield
5) https://demo.jmix.io/sampler/#main/10/sample?id=propertyfilter-dateinterval

**Comment by glaschenko** [comment]
@GlebDurygin sorry, my bad!
